import { useAppContext } from '@/app/context/app.context';
import type { Metadata } from 'next'
import { redirect } from 'next/navigation';
import { useEffect } from 'react'

// export const metadata: Metadata = {
//   title: 'Карандаш',
//   description: 'Generated by create next app',
// }

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <>
      {children}
    </>
  )
}
