export enum UserRoles {
    ADMIN = 'ADMIN',
    HEADCOMPANY = 'HEADCOMPANY',
    GLBUX = 'GLBUX',
    ZAMGLBUX = 'ZAMGLBUX',
    TANDIR = 'TANDIR',
    HEADSECTION = 'HEADSECTION',
    DELIVERY = 'DELIVERY',
    SELLER = 'SELLER',
    GUEST = 'GUEST',
    ZP = 'ZP',
    KASSIR = 'KASSIR',
    USER = 'USER',
    SIMPLE = 'SIMPLE'
}

